Update and simplification of template.
- scripts are pure shell.
- scripts run in faster with bg processes
- added RSS support with Pandoc
- Added a dummy demo example site.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,12 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env sh
 #
 # Invoke pandoc on $SRC, copy $STATIC assets over to $DST.
 #
 
 set -e
-shopt -s nullglob
 
-ROOT=$(dirname "$0")/..
+ROOT=$(dirname "$(dirname "$0")")
 # shellcheck source=bin/env
 . "$ROOT"/bin/env
 # shellcheck source=bin/logging
@@ -14,23 +13,68 @@ ROOT=$(dirname "$0")/..
 
 mkdir -p "$DST"
 
-status "Rendering"
-for file in "$SRC"/{,**/}*."${SRC_EXT}"; do
+convert() {
+  file="$1"
   # Strip `src` path from file string
-  FROM="${file##$SRC}"
+  FROM="${file##"$SRC"}"
+
+  # Apply the mappings as follows:
+  #  src/some/path/webpage.md --> public/some/path/webpage/index.html
+  #  src/some/path/index.md   --> public/some/path/index.html
+  # In order words: Let the file name become the slug name
+  # and let any index page simply become an index.hml page.
+  filename=$(basename "$FROM")
+  if echo "$filename" | grep -q 'index\.md$'; then
+    TO="${FROM%%"$SRC_EXT"}$DST_EXT"
+  else
+    TO="${FROM%%".$SRC_EXT"}/index.$DST_EXT"
+  fi
   # Define a target file with the new extension
-  TO="${FROM%%$SRC_EXT}$DST_EXT"
   echo "$FROM --> $TO"
   mkdir -p "$(dirname "$DST$TO")"
   # shellcheck disable=SC2086
-  pandoc $PANOPTS $file --output=$DST$TO || warn "Failed to create $TO"
-done
+  pandoc $PANOPTS "$file" --output="$DST$TO" || warn "Failed to create $TO"
+}
 
-status "Copying over assets"
-for file in "$STATIC"/{,**/}*.*; do
+copy() {
+  file="$1"
   FROM=$file
-  TO="$DST${file##$STATIC}"
-  echo "${FROM##$ROOT} --> ${TO##$ROOT}"
+  TO="$DST${file##"$STATIC"}"
+  echo "${FROM##"$ROOT"} --> ${TO##"$ROOT"}"
   mkdir -p "$(dirname "$TO")"
   cp "$FROM" "$TO" || warn "Failed to copy asset $TO"
+}
+
+status "Rendering"
+find "$SRC" -type f -name "*.$SRC_EXT" | while IFS= read -r file; do
+  convert "$file" &
 done
+wait
+
+status "Copying over assets"
+find "$STATIC" -type f | while IFS= read -r file; do
+  copy "$file" &
+done
+wait
+
+status "Rendering RSS feed"
+# This does the following:
+# 1. Get all the markdown files in $SRC that are not in "zettel" or an index
+# 2. Parse the "date" field from the YAML section, sort the files by date
+# 3. Print out only the paths to the files.
+ORDERED_POSTS=$({
+  find "$SRC" -type f -name "*.md" -not -path "$SRC/zettel/" | grep -v "index.md$" \
+  | xargs grep "date:" | awk -F ": " '{print $1 " " $2}' | sort -k 2r \
+  | awk -F ":" '{print $1}'
+})
+echo "$ORDERED_POSTS"
+# shellcheck disable=SC2086
+pandoc-rss -s \
+    -t "My Pandoc Blog" \
+    -d "A blog built with Pandaoc" \
+    -l "https://github.com/alxmrs/pandoc-website-template" \
+    -f "%s/" \
+    -c "MIT or CC BY-SA 4.0" \
+    -w "you@example.com (Jane Doe)" \
+    -n "en-US" \
+    $ORDERED_POSTS > "$DST/rss.xml"
