Project Grooming (#16)
- Added explainer to README.md
- Cleaned up the core build script
- Change default output dir to `public`
- Extracted out a `logging` script

Co-authored-by: Alex Rosengarten <alxrsngrtn@google.com>

diff --git a/tools/build b/tools/build
--- a/tools/build
+++ b/tools/build
@@ -1,57 +1,39 @@
 #!/bin/sh
 
+set -e
+
 ROOT=$(dirname $0)/..
-DEST=${DEST:-"$ROOT/docs"}
 SRC=${SRC:-"$ROOT/src"}
+DST=${DST:-"$ROOT/public"}
 HEADER=${HEADER:-"$SRC/header.html"}
 FOOTER=${FOOTER:-"$SRC/footer.html"}
 CSS=${CSS:-"css/main.css"}
-SRCEXT=${SRCEXT:-"md"}
-DSTEXT=${DSTEXT:-"html"}
+SRC_EXT=${SRC_EXT:-"md"}
+DST_EXT=${DST_EXT:-"html"}
 PANOPTS=${PANOPTS:-"--css $CSS --email-obfuscation=javascript --metadata-file=defaults.yml -f gfm -t html5 -B $HEADER -A $FOOTER"}
 
+. $ROOT/tools/logging
 
-RED="\033[91m"
-GRN="\033[92m"
-MAG="\033[95m"
-BLD="\033[1m"
-END="\033[0m"
-
-warn() {
-    echo "$RED$BLD$1$END"
-}
-
-fail() {
-    warn $1
-    exit 1
-}
-
-status() {
-    echo "$MAG$1$END"
-}
-
-mkdir -p $DEST
-
+mkdir -p $DST
 
 status "Rendering"
-
-for file in `find $SRC -name "*.$SRCEXT" -type f` 
-do 
-   from="${file##$SRC}" # Strip `src` path from file string
-   to="${from%%$SRCEXT}$DSTEXT"
-   echo "$from --> $to"
-   mkdir -p $(dirname "$DEST$to")
-   pandoc $PANOPTS --output=$DEST$to $file || warn "failed to create $to"
+for file in `find $SRC -name "*.$SRC_EXT" -type f`
+do
+   # Strip `src` path from file string
+   FROM="${file##$SRC}"
+   # Define a target file with the new extension
+   TO="${FROM%%$SRC_EXT}$DST_EXT"
+   echo "$FROM --> $TO"
+   mkdir -p $(dirname "$DST$TO")
+   pandoc $PANOPTS --output=$DST$TO $file || warn "failed TO create $TO"
 done
 
-
 status "Copying over assets"
-
-for file in `find $SRC ! -name "*.$SRCEXT" -type f`
+for file in `find $SRC ! -name "*.$SRC_EXT" -type f`
 do 
-    from=$file
-    to="$DEST${file##$SRC}"
-    echo "${from##$ROOT} --> ${to##$ROOT}"
-    mkdir -p $(dirname $to)
-    cp $from $to || warm "Failed to copy asset $to"
+    FROM=$file
+    TO="$DST${file##$SRC}"
+    echo "${FROM##$ROOT} --> ${TO##$ROOT}"
+    mkdir -p $(dirname $TO)
+    cp $FROM $TO || warm "Failed TO copy asset $TO"
 done
